service: ocr
provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: dev

package:
  patterns:
    - "!./**"
    - "./bin/**"

functions:
  ocr:
    handler: bin/ocr
    events:
      - http:
          path: /
          method: get
          cors: true
          private: false

