service: ocr
frameworkVersion: "^3.33.0"

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: dev

layers:
  tesseract:
    path: layers/tesseract-al2
    compatibleRuntimes:
      - "go1.x"

package:
  patterns:
    - "!./**"
    - "./bin/**"

functions:
  ocr:
    handler: bin/ocr
    events:
      - http:
          path: /
          method: get

