name: auto-deploy
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  ssh:
    name: script-runner
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild & Update
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}

          script: cd ocr && make prod
